SOURCE_DIRECTORY := $(1)
BACKUP_DIRECTORY := $(2)
INTERVAL := $(3)
MAX_BACKUPS := $(4)

create-directory:
	./directory.sh "$(SOURCE_DIRECTORY)" 
	./directory.sh "$(BACKUP_DIRECTORY)"

run: create-directory
	./backup.sh "$(SOURCE_DIRECTORY)" "$(BACKUP_DIRECTORY)" $(INTERVAL) $(MAX_BACKUPS)
